INSERT INTO PERSON (ID,EMAIL,FIRST_NAME,JOINED_DATE,LAST_NAME) VALUES (1,'John.Smith@gmail.com','John','2020-01-04','Smith');
INSERT INTO PERSON (ID,EMAIL,FIRST_NAME,JOINED_DATE,LAST_NAME) VALUES (2,'John.Smith2@gmail.com','John2','2020-01-04','Smith2');
INSERT INTO PERSON (ID,EMAIL,FIRST_NAME,JOINED_DATE,LAST_NAME) VALUES (3,'John.Smith3@gmail.com','John3','2020-01-04','Smith3');
INSERT INTO PERSON (ID,EMAIL,FIRST_NAME,JOINED_DATE,LAST_NAME) VALUES (4,'John.Smith4@gmail.com','John4','2020-01-04','Smith4');